remote_theme: just-the-docs/just-the-docs

title: Symfony Add-on Pack
description: Symfony Add-on Pack is a collection of extra Symfony components that you can use in your Symfony applications.

aux_links:
  Visit repository on GitHub: https://github.com/darkwebdesign/symfony-addon-pack

collections:
  2_0:
    permalink: "/docs/:collection/:path:output_ext"
    output: true
  1_0:
    permalink: "/docs/:collection/:path:output_ext"
    output: true
  test:
    permalink: "/docs/:collection/:path:output_ext"
    output: true

just_the_docs:
  collections:
    2_0:
      name: v2.0 (latest)
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    1_0:
      name: v1.0
      nav_exclude: false
      nav_fold: true
      search_exclude: true
    test:
      name: Test
      nav_exclude: false
      nav_fold: true
      search_exclude: true

footer_content: "Copyright &copy; 1996-2023 DarkWeb Design."
